server:
  port: 8023

# 应用名称 （nacos会将该名称当做服务名称）
spring:
  application:
    name: product-service
  cloud:
    nacos:
      server-addr: 172.16.10.132:8847 # 服务地址
      discovery:
        username: nacos
        password: nacos
#        namespace: public
